import {
  pgTable,
  pgEnum,
  uuid,
  text,
  timestamp,
  boolean,
  integer,
  primaryKey,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// ─── Enums ───────────────────────────────────────────────────────────────────

export const userRoleEnum = pgEnum("user_role", ["owner", "admin"]);

export const serviceStatusEnum = pgEnum("service_status", [
  "operational",
  "degraded",
  "down",
]);

export const incidentSeverityEnum = pgEnum("incident_severity", [
  "minor",
  "major",
  "critical",
]);

export const incidentStatusEnum = pgEnum("incident_status", [
  "investigating",
  "identified",
  "monitoring",
  "resolved",
]);

// ─── Tables ──────────────────────────────────────────────────────────────────

export const orgs = pgTable("orgs", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  orgId: uuid("org_id")
    .notNull()
    .references(() => orgs.id),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  name: text("name").notNull(),
  role: userRoleEnum("role").notNull().default("admin"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const services = pgTable("services", {
  id: uuid("id").primaryKey().defaultRandom(),
  orgId: uuid("org_id")
    .notNull()
    .references(() => orgs.id),
  name: text("name").notNull(),
  description: text("description"),
  status: serviceStatusEnum("status").notNull().default("operational"),
  statusChangedAt: timestamp("status_changed_at").notNull().defaultNow(),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const incidents = pgTable("incidents", {
  id: uuid("id").primaryKey().defaultRandom(),
  orgId: uuid("org_id")
    .notNull()
    .references(() => orgs.id),
  title: text("title").notNull(),
  severity: incidentSeverityEnum("severity").notNull(),
  status: incidentStatusEnum("status").notNull(),
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  resolvedAt: timestamp("resolved_at"),
});

export const incidentServices = pgTable(
  "incident_services",
  {
    incidentId: uuid("incident_id")
      .notNull()
      .references(() => incidents.id, { onDelete: "cascade" }),
    serviceId: uuid("service_id")
      .notNull()
      .references(() => services.id, { onDelete: "restrict" }),
  },
  (t) => [primaryKey({ columns: [t.incidentId, t.serviceId] })]
);

export const incidentUpdates = pgTable("incident_updates", {
  id: uuid("id").primaryKey().defaultRandom(),
  incidentId: uuid("incident_id")
    .notNull()
    .references(() => incidents.id, { onDelete: "cascade" }),
  message: text("message").notNull(),
  statusAtTime: incidentStatusEnum("status_at_time").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  authorId: uuid("author_id")
    .notNull()
    .references(() => users.id),
});

// ─── Relations ───────────────────────────────────────────────────────────────

export const orgsRelations = relations(orgs, ({ many }) => ({
  users: many(users),
  services: many(services),
  incidents: many(incidents),
}));

export const usersRelations = relations(users, ({ one, many }) => ({
  org: one(orgs, { fields: [users.orgId], references: [orgs.id] }),
  incidentUpdates: many(incidentUpdates),
}));

export const servicesRelations = relations(services, ({ one, many }) => ({
  org: one(orgs, { fields: [services.orgId], references: [orgs.id] }),
  incidentServices: many(incidentServices),
}));

export const incidentsRelations = relations(incidents, ({ one, many }) => ({
  org: one(orgs, { fields: [incidents.orgId], references: [orgs.id] }),
  incidentServices: many(incidentServices),
  incidentUpdates: many(incidentUpdates),
}));

export const incidentServicesRelations = relations(
  incidentServices,
  ({ one }) => ({
    incident: one(incidents, {
      fields: [incidentServices.incidentId],
      references: [incidents.id],
    }),
    service: one(services, {
      fields: [incidentServices.serviceId],
      references: [services.id],
    }),
  })
);

export const incidentUpdatesRelations = relations(
  incidentUpdates,
  ({ one }) => ({
    incident: one(incidents, {
      fields: [incidentUpdates.incidentId],
      references: [incidents.id],
    }),
    author: one(users, {
      fields: [incidentUpdates.authorId],
      references: [users.id],
    }),
  })
);
