import { NextResponse } from "next/server";
import { db } from "@/db";
import { services, incidents, incidentServices, incidentUpdates, users } from "@/db/schema";
import { eq, and, ne, lt } from "drizzle-orm";

export async function GET(req: Request) {
  // 1. Cron Secret Security Guard (Vercel standard)
  const authHeader = req.headers.get("Authorization");
  const cronSecret = process.env.CRON_SECRET;

  if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const thresholdMinutes = parseInt(process.env.AUTO_DETECTION_THRESHOLD_MINUTES || "5", 10);
    const thresholdTime = new Date(Date.now() - thresholdMinutes * 60 * 1000);

    // Find services where status = 'down' and statusChangedAt < thresholdTime
    const downServices = await db
      .select()
      .from(services)
      .where(and(eq(services.status, "down"), lt(services.statusChangedAt, thresholdTime)));

    const created: string[] = [];
    const skipped: string[] = [];

    // Find a system user to author the auto-generated updates (first admin/owner user)
    const systemUsers = await db.select().from(users).limit(1);
    const systemAuthor = systemUsers[0];

    if (!systemAuthor) {
      return NextResponse.json({ error: "No system author user configured. Create an admin account first." }, { status: 500 });
    }

    for (const service of downServices) {
      // Check if there is an active/open incident linked to this service
      const openIncidentLinks = await db
        .select({ incidentId: incidentServices.incidentId })
        .from(incidentServices)
        .innerJoin(incidents, eq(incidentServices.incidentId, incidents.id))
        .where(
          and(
            eq(incidentServices.serviceId, service.id),
            ne(incidents.status, "resolved")
          )
        );

      if (openIncidentLinks.length > 0) {
        skipped.push(service.name);
        continue;
      }

      // No open incident exists — trigger auto-incident creation
      const title = `⚠️ ${service.name} outage auto-detected`;
      const updateMessage = `⚠️ ${service.name} has been down for over ${thresholdMinutes} minutes without an update. This incident was auto-generated.`;

      const incident = await db.transaction(async (tx) => {
        // Create Incident
        const [newIncident] = await tx
          .insert(incidents)
          .values({
            orgId: service.orgId,
            title,
            severity: "major",
            status: "investigating",
            isAutoGenerated: true,
          })
          .returning();

        // Link Service
        await tx.insert(incidentServices).values({
          incidentId: newIncident.id,
          serviceId: service.id,
        });

        // Post Timeline Update
        const [update] = await tx
          .insert(incidentUpdates)
          .values({
            incidentId: newIncident.id,
            message: updateMessage,
            statusAtTime: "investigating",
            authorId: systemAuthor.id,
          })
          .returning();

        return { newIncident, update };
      });

      // Dispatch SSE Event for real-time subscribers
      const { sseEmitter } = await import("@/lib/sse");
      sseEmitter.emit("incident-created", {
        ...incident.newIncident,
        updates: [incident.update],
        serviceIds: [service.id],
      });

      created.push(service.name);
    }

    return NextResponse.json({
      status: "success",
      checkedCount: downServices.length,
      incidentsCreated: created,
      skippedActive: skipped,
    });
  } catch (err) {
    console.error(err);
    return NextResponse.json({ error: "Auto-detection execution failed" }, { status: 500 });
  }
}
